spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auction
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialec: org.hibernate.dialect.MySQLDialect