package com.example.sprintboot.entity;
// Generated Oct 8, 2018 8:48:14 AM by Hibernate Tools 5.2.5.Final


import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * LicenseCars generated by hbm2java
 */
@Entity
@Table(name="license_cars"
    ,catalog="auction"
)
public class LicenseCars  implements java.io.Serializable {


     private Long seq;
     private Long version;
     private LocalDateTime auctionDate;
     private long auctionTime;
     private String createBy;
     private LocalDateTime createDate;
     private LocalDate endRegisterDate;
     private Long firstprice;
     private String imageLicenseCar;
     private String number;
     private LocalDate startRegisterDate;
     private String status;
     private String updateBy;
     private LocalDateTime updateDate;

    public LicenseCars() {
    }

	
    public LicenseCars(long auctionTime) {
        this.auctionTime = auctionTime;
    }
    public LicenseCars(LocalDateTime auctionDate, long auctionTime, String createBy, LocalDateTime createDate, LocalDate endRegisterDate, Long firstprice, String imageLicenseCar, String number, LocalDate startRegisterDate, String status, String updateBy, LocalDateTime updateDate) {
       this.auctionDate = auctionDate;
       this.auctionTime = auctionTime;
       this.createBy = createBy;
       this.createDate = createDate;
       this.endRegisterDate = endRegisterDate;
       this.firstprice = firstprice;
       this.imageLicenseCar = imageLicenseCar;
       this.number = number;
       this.startRegisterDate = startRegisterDate;
       this.status = status;
       this.updateBy = updateBy;
       this.updateDate = updateDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)


    @Column(name="seq", unique=true, nullable=false)
    public Long getSeq() {
        return this.seq;
    }
    
    public void setSeq(Long seq) {
        this.seq = seq;
    }

    @Version
    @Column(name="version")
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

    
    @Column(name="auction_date", length=26)
    public LocalDateTime getAuctionDate() {
        return this.auctionDate;
    }
    
    public void setAuctionDate(LocalDateTime auctionDate) {
        this.auctionDate = auctionDate;
    }

    
    @Column(name="auction_time", nullable=false)
    public long getAuctionTime() {
        return this.auctionTime;
    }
    
    public void setAuctionTime(long auctionTime) {
        this.auctionTime = auctionTime;
    }

    
    @Column(name="create_by", length=45)
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    
    @Column(name="create_date", length=26)
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="end_register_date", length=10)
    public LocalDate getEndRegisterDate() {
        return this.endRegisterDate;
    }
    
    public void setEndRegisterDate(LocalDate endRegisterDate) {
        this.endRegisterDate = endRegisterDate;
    }

    
    @Column(name="firstprice")
    public Long getFirstprice() {
        return this.firstprice;
    }
    
    public void setFirstprice(Long firstprice) {
        this.firstprice = firstprice;
    }

    
    @Column(name="image_license_car", length=45)
    public String getImageLicenseCar() {
        return this.imageLicenseCar;
    }
    
    public void setImageLicenseCar(String imageLicenseCar) {
        this.imageLicenseCar = imageLicenseCar;
    }

    
    @Column(name="number", length=10)
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }

    
    @Column(name="start_register_date", length=10)
    public LocalDate getStartRegisterDate() {
        return this.startRegisterDate;
    }
    
    public void setStartRegisterDate(LocalDate startRegisterDate) {
        this.startRegisterDate = startRegisterDate;
    }

    
    @Column(name="status", length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="update_by", length=45)
    public String getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    
    @Column(name="update_date", length=26)
    public LocalDateTime getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }




}


