package com.example.sprintboot.entity;
// Generated Oct 8, 2018 8:48:14 AM by Hibernate Tools 5.2.5.Final


import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * RegisterAuction generated by hbm2java
 */
@Entity
@Table(name="register_auction"
    ,catalog="auction"
)
public class RegisterAuction  extends FwEntity implements java.io.Serializable {


     private Long seq;
     private Long version;
     private String createBy;
     private LocalDateTime createDate;
     //private long licenseCarId;
     private LocalDate registerDate;
     private String updateBy;
     private LocalDateTime updateDate;
     //private long userId;
     private User user;
     private LicenseCars licenseCars;

    public RegisterAuction() {
    }

    public RegisterAuction(Long seq, Long version, String createBy, LocalDateTime createDate, LocalDate registerDate, String updateBy, LocalDateTime updateDate, User user, LicenseCars licenseCars) {
        this.seq = seq;
        this.version = version;
        this.createBy = createBy;
        this.createDate = createDate;
        this.registerDate = registerDate;
        this.updateBy = updateBy;
        this.updateDate = updateDate;
        this.user = user;
        this.licenseCars = licenseCars;
    }

    @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="seq", unique=true, nullable=false)
    public Long getSeq() {
        return this.seq;
    }
    
    public void setSeq(Long seq) {
        this.seq = seq;
    }

    @Version
    @Column(name="version")
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

    
    @Column(name="create_by", length=45)
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    
    @Column(name="create_date", length=26)
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }


    
    @Column(name="register_date", length=10)
    public LocalDate getRegisterDate() {
        return this.registerDate;
    }
    
    public void setRegisterDate(LocalDate registerDate) {
        this.registerDate = registerDate;
    }

    
    @Column(name="update_by", length=45)
    public String getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    
    @Column(name="update_date", length=26)
    public LocalDateTime getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }


    @ManyToOne
    @JoinColumn(name = "user_id")
    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @ManyToOne
    @JoinColumn(name = "license_car_id")
    public LicenseCars getLicenseCars() {
        return licenseCars;
    }

    public void setLicenseCars(LicenseCars licenseCars) {
        this.licenseCars = licenseCars;
    }
}


