package com.example.sprintboot.entity;
// Generated Oct 8, 2018 8:48:14 AM by Hibernate Tools 5.2.5.Final


import java.time.LocalDateTime;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * SaveAuction generated by hbm2java
 */
@Entity
@Table(name="save_auction"
    ,catalog="auction"
)
public class SaveAuction  extends FwEntity implements java.io.Serializable {


     private Long seq;
     private Long version;
     private String createBy;
     private LocalDateTime createDate;
     private LocalDateTime endAuctionDate;
     private Long finalprice;
     private String updateBy;
     private LocalDateTime updateDate;
     private LicenseCars licenseCars;
     private User user;

    public SaveAuction() {
    }


    public SaveAuction(Long seq, Long version, String createBy, LocalDateTime createDate, LocalDateTime endAuctionDate, Long finalprice, String updateBy, LocalDateTime updateDate, LicenseCars licenseCarsId, User user) {
        this.seq = seq;
        this.version = version;
        this.createBy = createBy;
        this.createDate = createDate;
        this.endAuctionDate = endAuctionDate;
        this.finalprice = finalprice;
        this.updateBy = updateBy;
        this.updateDate = updateDate;
        this.licenseCars = licenseCarsId;
        this.user = user;
    }

    @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="seq", unique=true, nullable=false)
    public Long getSeq() {
        return this.seq;
    }
    
    public void setSeq(Long seq) {
        this.seq = seq;
    }

    @Version
    @Column(name="version")
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

    
    @Column(name="create_by", length=45)
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    
    @Column(name="create_date", length=26)
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="end_auction_date", length=26)
    public LocalDateTime getEndAuctionDate() {
        return this.endAuctionDate;
    }
    
    public void setEndAuctionDate(LocalDateTime endAuctionDate) {
        this.endAuctionDate = endAuctionDate;
    }

    
    @Column(name="finalprice")
    public Long getFinalprice() {
        return this.finalprice;
    }
    
    public void setFinalprice(Long finalprice) {
        this.finalprice = finalprice;
    }

    @OneToOne
    @JoinColumn(name = "user_id")
    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }


    
    @Column(name="update_by", length=45)
    public String getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    
    @Column(name="update_date", length=26)
    public LocalDateTime getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }


    @OneToOne
    @JoinColumn(name = "license_cars_id")
    public LicenseCars getLicenseCars() {
        return licenseCars;
    }

    public void setLicenseCars(LicenseCars licenseCarsId) {
        this.licenseCars = licenseCarsId;
    }
}


